# Generated by Django 3.2.8 on 2021-12-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_active',
            new_name='is_done',
        ),
    ]
