# Generated by Django 3.2.8 on 2021-12-19 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_auto_20211219_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_link',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='Ссылка на репозиторий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Работают над проектом'),
        ),
    ]
